### ISSUE TITLE
Show error messages

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran-lsp#22]
When there is a semantic error, we should show error messages, right now it doesn't do anything:

<img width="525" alt="image" src="https://github.com/user-attachments/assets/6971d50d-e6a0-4dc9-b0bb-2da2f672f862">

I would expect this to underline `xx`, like LFortran does in a terminal:
```
$ lfortran --show-asr expr2.f90
semantic error: Variable 'xx' is not declared
 --> expr2.f90:7:10
  |
7 | print *, xx
  |          ^^ 'xx' is undeclared
```

**Comment by dylon** [comment]
This seems to work in the latest versions of lfortran and lfortran-lsp, so I will close it for now. If the problem persists, please reopen this issue:

![image](https://github.com/user-attachments/assets/25c50f0e-afa9-4eed-9f85-d217b533f2de)

**Comment by certik** [comment]
I just tested the latest LFortran and lfortran-lsp, and it does not work on macOS. The same symptoms as above.

**Comment by Pranavchiku** [comment]
I cannot see the squiggle, but the outline issue is fixed.

**Comment by certik** [comment]
It actually works now:

lfortran --show-errors /var/folders/vg/lymvsp1153sgwwfdh3pm45hw0000gn/T/lfortran-lsp-45314-jBVuIC1bLSGg-.tmp

But one must compile with `WITH_JSON=true` and the default error that you get is:
```
Compiler was not configured with LSP support (-DWITH_LSP), please build it again.
```
Which it should say `WITH_JSON`, not `WITH_LSP`, and we should not need WITH_JSON anyway, now when we include our own json.

Finally, the lfortran-lsp must show the above error message correctly, it just silences it.

**Comment by Pranavchiku** [comment]
```
Compiler was not configured with LSP support (-DWITH_LSP), please build it again.
````

is fixed, I am now looking at why LFortran returns only one error with `--continue-compilation` in json, it works with `--show-asr`. I think the new implementation of LFortranJSON through https://github.com/lfortran/lfortran/pull/5750 messed it up.

**Comment by certik** [comment]
@Pranavchiku you have to recompile LFortran with `WITH_JSON=true`, then you'll see the red squiggle.

**Comment by Pranavchiku** [comment]
> then you'll see the red squiggle.

Yes, also with the following diff you don't need `-DWITH_JSON=yes`

```diff
diff --git a/src/bin/lfortran.cpp b/src/bin/lfortran.cpp
index ac30931b5..35b27753d 100644
--- a/src/bin/lfortran.cpp
+++ b/src/bin/lfortran.cpp
@@ -2555,12 +2555,7 @@ int main_app(int argc, char *argv[]) {
     }
 
     if (show_errors) {
-#ifdef HAVE_LFORTRAN_RAPIDJSON
         return get_errors(arg_file, compiler_options);
-#else
-        std::cerr << "Compiler was not configured with LSP support (-DWITH_LSP), please build it again." << std::endl;
-        return 1;
-#endif
     }
     lfortran_pass_manager.use_default_passes();
     if (show_llvm) {
```

**Comment by certik** [comment]
We should remove rapidjson completely.

**Comment by Pranavchiku** [comment]
For that we need to make LFortranJSON robust to support `--show-json`.

**Comment by Pranavchiku** [comment]
I have fix for this ready, pushing PR

<img width="342" alt="image" src="https://github.com/user-attachments/assets/593142ac-f7c0-4882-b927-b131f1d0d9f4" />

**Comment by Pranavchiku** [comment]
PR: https://github.com/lfortran/lfortran/pull/5767

**Comment by certik** [comment]
I can confirm that this now works:

<img width="573" alt="image" src="https://github.com/user-attachments/assets/2bc16b7e-7a85-4a6d-9130-c1a9c02efe29" />
