### ISSUE TITLE
code completion does not work

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran-lsp#25]
This should show `program1` as a possible completion:

![image](https://github.com/user-attachments/assets/ef0c45b7-ad63-47ac-aa68-dbab0810ea74)

**Comment by dylon** [comment]
The definition preview is indexed the same way as described here: https://github.com/lfortran/lfortran-lsp/issues/24. I will leave this open for now, but once the latter is resolved so too will this one be resolved.

**Comment by certik** [comment]
It seems to work now. I'll leave this open to test this more, but the basic code completion seems to work.

**Comment by certik** [comment]
Here is one bug: the completion doesn't work inside derived types:
```
program derived_types_28
    implicit none
    type t
        real, dimension(:), pointer :: x, y, z
    end type t

    type(t) :: type
    real, target :: r(1)
    real :: ans
    r = 34
    type%x => r
    type%y => r
    type%z => r
    type%

    type%x = type%y + type%z

    ans = type%x(1)
    print *, ans

    if (abs(ans - 68.0) > 1e-5) error stop
end program
```
On the line `type%` it will not complete anything.

**Comment by Pranavchiku** [comment]
With https://github.com/lfortran/lfortran-lsp/pull/37. All these are because we were not using `--continue-compilation`

<img width="513" alt="image" src="https://github.com/user-attachments/assets/49562c52-3437-40be-a555-a9b3c26e3729" />

**Comment by Pranavchiku** [comment]
<img width="634" alt="image" src="https://github.com/user-attachments/assets/30d91cc1-393d-4f33-9d91-90b755d246c0" />


This is still a bug. I'm opening separate issue for this.

**Comment by certik** [comment]
The basic code completion now works:

<img width="653" alt="image" src="https://github.com/user-attachments/assets/965e8b16-946d-4c35-896a-c40e11ec2e61" />


But as you can see, it offers the symbol xx124 as well, but that's the name of the program, so we should know in ASR that a program symbol cannot be used inside `print`. That is a seperate issue to filter the symbols based on what fits in the current position.
