### ISSUE TITLE
Document how to debug the extension and see its communication with lfortran

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran-lsp#27]
When something doesn't work, it would be nice to see what exact lfortran command line was executed, so that one can determine if this is a bug in lfortran, or in lfortran-lsp and then go from there.

Document in README how to see these logs.

**Comment by dylon** [comment]
The README has been updated to describe how to configure logging as part of https://github.com/lfortran/lfortran-lsp/pull/29: https://lfortran.github.io/lfortran-lsp/
