### ISSUE TITLE
Add a CI to test this extension

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran-lsp#3]
I don't know if the testing instructions at https://code.visualstudio.com/api/working-with-extensions/testing-extension can be run at a CI or not.

Ideally we install the extension into some headless VSCode, install a given version of LFortran, and then test things like looking up definitions using some javascript test file.

That way this setup will ensure that everything actually runs, and also act as documentation how to install everything and which exact versions work together.

Related to that but a separate issue is to automatically publish the extension for VSCode: https://github.com/lfortran/lfortran-lsp/issues/4.

**Comment by dylon** [comment]
This was completed as part of https://github.com/lfortran/lfortran-lsp/pull/16.
